import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/shared/Footer";
import { Toaster } from "sonner";
import QueryProvider from "@/provider/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-[#F9FAFB]`}>
        <Toaster />
        <QueryProvider>{children}</QueryProvider>
        <Footer />
      </body>
    </html>
  );
}
